### ISSUE TITLE
高性能日志模块

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#1]
现在日志是一把写文件大锁加上去的。需要更加细粒度。不然写日志竞争很大。要改成异步后台日志线程写。这个在知名网络开源库muduo中有实现，可以参考。并且日志支持配置，比如旋转天数等等。

调查各种各样的C++ Log库 https://stackoverflow.com/questions/439791/what-is-the-most-efficient-thread-safe-c-logger
http://www.pantheios.org/performance.html#scenarios

从资料中得到的结果，虽然是改进日志模块性能，首先，就单独对比性能来说，虽然boost对比其他第三方库没有压倒性的优势，但也没有劣势，而且从功能和性能的权衡角度看，boost也是绝对满足项目本身的要求的。

采用boost log的优缺点： 
- 缺点：boost 接口不友好，复杂。
- 优点：功能强大（包括可以日志输出可以重定向到远端节点，考虑以后日志汇总监控，会方便），而且项目本身依赖boost，可以直接引用。不用引入冗余的第三方日志库

采用第三方日志库的优缺点：
- 缺点： 功能冗余引入。
- 优点： 接口友好，功能简单，够用。

**Comment by AlexiaChen** [comment]
Solved #28

**Comment by AlexiaChen** [comment]
#
