### ISSUE TITLE
在windows平台上使用exportwallet命令时报“Must be an absolute path”错误

### ISSUE THREAD

**Issue by chajiubu** [bigbangcore/BigBang#117]
如题。看了一下代码，发现问题发生在RPCExportWallet这个方法中。  

    auto spParam = CastParamPtr<CExportWalletParam>(param);  
    fs::path pSave(string(spParam->strPath));  
    if (!pSave.is_absolute())  
    {  
        throw CRPCException(RPC_WALLET_ERROR, "Must be an absolute path.");  
    }

**Comment by AlexiaChen** [comment]
Additional information could help you

Access windows native directory from cygwin enviroment with absolute path:
/cygdrive/[c | d | e | f]/[your file name]

- https://superuser.com/questions/229870/how-to-access-different-directories-outside-cygwin-home-dir
- https://stackoverflow.com/questions/1850920/how-to-navigate-to-a-directory-in-c-with-cygwin
