### ISSUE TITLE
求助：关于Bigbang的一些问题

### ISSUE THREAD

**Issue by erzaxs** [bigbangcore/BigBang#122]
update:
  answered at: https://github.com/bigbangcore/BigBang/issues/122#issuecomment-535728912

----
原问题：

- `-debug` 参数所指的调试模式具体指的是什么？是指本地独立的链吗？还是说只是打印调试日志？

- 如何搭建和使用本地独立的链？类似于bitcoin `-regtest`，或者eth ganache

- 测试链除了挖矿外，有没有水龙头可以获取token？测试链我如何知道我是否同步到了最新的块？

**Comment by chajiubu** [comment]
- 不是独立的链，-debug是对应与-release来说的  
- 配置文件bigbang.config中不设置连接私有节点或者不设置bigbang.config，就是私有的链了
- 没有水龙头，目前只能通过挖矿获得token。您可以使用bigbang listpeer查看各个节点的高度height，再使用bigbang getblockcount获得区块数量，两者对比就知道是不是同步到了最新的块了

**Comment by erzaxs** [comment]
感谢 @chajiubu 

第二波问题来了。

---
update:

这层的问题在这里回答了：
https://github.com/bigbangcore/BigBang/issues/122#issuecomment-536244904

---

1. 出块周期是多少？私有链如何调整出块间隔？开发环境中较短的出块间隔可以提高开发效率。。
2. 不同链上（mainnet/testnet/private_net)地址是否有差异？同一个私钥在不同的连上推导出的地址是一样的吗？
3. pow挖矿产出量一个块是多少？balance是如何对应的？(我在挖矿1分钟后getbalance->.Avail 为 0.02 ,不清楚这个如何计算的)
4. 可以详细解释下pow挖矿和冷钱包模版挖矿的细节吗？假设我用冷钱包模版挖矿，cryptonightAddress、cryptonightKey 具体作用是什么？addnewtemplate mint获得的模版地址有什么用？我挖到的币在哪个地址上？我如何花费这些挖到的币？
5. pow挖矿在block中有数据反映吗？如果是类似于bitcoin 的coinbase，为什么我getblock到的数据tx都是空的
6. 关于模版，除了白皮书外有更为详细的文档吗？

**Comment by erzaxs** [comment]
自己回答：

>出块周期是多少？私有链如何调整出块间隔？开发环境中较短的出块间隔可以提高开发效率。。

目前无法调整出块周期

>pow挖矿产出量一个块是多少？balance是如何对应的？(我在挖矿1分钟后getbalance->.Avail 为 0.02 ,不清楚这个如何计算的)

pow出块奖励按照出块分布计算,参考：https://github.com/bigbangcore/BigBang/wiki/%E5%87%BA%E5%9D%97%E5%A5%96%E5%8A%B1%E5%88%86%E5%B8%83 ，pow总量/块数（总时间/出块间隔）得到每个块的奖励量，精度为6，计算得到小数

>可以详细解释下pow挖矿和冷钱包模版挖矿的细节吗？假设我用冷钱包模版挖矿，cryptonightAddress、cryptonightKey 具体作用是什么？addnewtemplate mint获得的模版地址有什么用？我挖到的币在哪个地址上？我如何花费这些挖到的币？

已知的信息包括：
cryptonightaddress：该参数为奖励可花费的地址，花费奖励TOKEN需要使用该地址对应的私钥才可以花费；
cryptonightkey：挖矿私钥，用于矿工打包签名的私钥
挖矿奖励在模版地址上，花费奖励需要cryptonightaddress对应私钥
额外的，这样设计与矿池挖矿有关

>关于模版，除了白皮书外有更为详细的文档吗

暂时没有

> pow挖矿在block中有数据反映吗？如果是类似于bitcoin 的coinbase，为什么我getblock到的数据tx都是空的

这个可以通过 listtransaction 和 gettransaction查到

**Comment by erzaxs** [comment]
暂时关闭这个Issue,后续如果有新的问题会再打开。

**Comment by erzaxs** [comment]
又一波新的问题

下述问题基于binary release version`v0.9.1` （macOS）

- 考虑到BigBang基于UTXO模型，主币交易是否支持多个输入来源于不同的地址？是否支持多个输出到超过2个的地址？举个例子：能否在一笔交易中使用A和B的utxo向C和D转账并找零给A。
- 类似于上个问题，转账只能发生在2个地址间吗？
    - 如果是只能发生在2个地址间，那么一笔交易必然只涉及到2个地址from和to
        - RPC API `gettransaction` 返回字段有`sendto`没有`sendFrom`，可以增加`sendFrom`字段吗？是否可以认为一笔交易的所有vin都来自于同一个地址？
- 交易能更细粒度的控制utxo吗？比如自己选择输入，自己指定输出。知否有相关RPC 的开放计划（比如查询utxo,指定vin/vout创建交易）？
- RPC API `listtransaction` 给出的结果似乎是按照区块高度升序排序的,是这样的吗？RPC文档描述似乎是最近的交易（理解上应该是区块高度降序）,应该在什么场景下使用这个RPC？
    - 我尝试查询最近的区块的交易（类似于比特币的listsinceblock）,直觉上`listtransaction`是比较适合的，实际上不可用（甚至在测试链上直接不能给出数据）。目前的做法是查询区块高度，然后逐块扫描交易
- RPC API `listtransaction` 和 `gettransaction`返回的数据结构不同（比如：`listtransaction`给出的交易数据包含`from`字段，两者的字段名字也有细微差别），这两个rpc给出的交易数据有什么差别？
