### ISSUE TITLE
误输入了一个错误的命令，没有返回数据，摁ctrl+c也没法退出

### ISSUE THREAD

**Issue by chajiubu** [bigbangcore/BigBang#123]
比如我们把bigbang lockkey 44e12b2bbfd627c2d8315571623874f58908fc4723514ee56cfc9f4be8e3ca3f这个命令错误的输为bigbang lock 44e12b2bbfd627c2d8315571623874f58908fc4723514ee56cfc9f4be8e3ca3f，这个时候就会出现如题描述的情况。

**Comment by AlexiaChen** [comment]
按照原题描述无法复现。版本号如下：

```txt
Bigbang version is v1.0.0, git commit id is 4cefc0950921235bf634389049ab0cba8dae3a9a:r
```
