### ISSUE TITLE
增强rpc功能，使得创建交易、交易签名可以在冷热节点上分步处理

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#138]
现在RPC新增交易虽然分离出了三个命令：createtransaction, signtransaction, sendtransaction

- [x] 但是createtransaction仅支持导入私钥，允许通过导入公钥来创建交易可增强私钥安全性。(不支持模板)

- [ ] signtransaction需要用到txpool，不支持冷节点签名。<del>可以改造为signtransaction仅用来签名</del> 这里打算通过一个新增的函数signofflinetransaction来进行离线签名，一个函数只做好一件事 (不支持模板)

**Comment by sunhantao** [comment]
createtransaction related issue #280

**Comment by AlexiaChen** [comment]
这个欧云已经在做相同的功能。
