### ISSUE TITLE
部分BLOCK中的TXID，使用gettransaction查询不到记录（偶现）

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#150]
通过高度查询到BLOCK HASH，然后通过getblock查询到BLOCK中的TXID，再使用gettransaction查询TX信息失败。

例：
bigbang> getblockhash 7989
[
    "1cc3f08c2ee7c1d46603eb6a61ff073c6e529e742547ae14cd87dc454f70bdaf"
]
bigbang> getblock 1cc3f08c2ee7c1d46603eb6a61ff073c6e529e742547ae14cd87dc454f70bdaf
{
    "hash" : "1cc3f08c2ee7c1d46603eb6a61ff073c6e529e742547ae14cd87dc454f70bdaf",
    "hashPrev" : "daaeb9dbb13f3e4b4c5e721da4de0f6eea144a88264aa43e8762390c79fba36d",
    "version" : 1,
    "type" : "primary-pow",
    "time" : 1569890985,
    "fork" : "69ed2d6ebb9ace57ca0c1e6eaa4d8eaa2db458bfaa37b37d1a9bfcec46ef099e",
    "height" : 7989,
    "txmint" : "5d92a2a91d3381b98ab01c61fad3fad4c3da72f9a3dda2c15ebb1217ce30a73e",
    "tx" : [
        "5d92a287edda0991591448112306f39ce53ea099a0ab3572b078e3f6cded363c",
        "5d92a287323d905112a1fc5e217f2caa4a93118bc782410bdec91fab723b6092"
    ],
    "prev" : "daaeb9dbb13f3e4b4c5e721da4de0f6eea144a88264aa43e8762390c79fba36d"
}
bigbang> gettransaction 5d92a287edda0991591448112306f39ce53ea099a0ab3572b078e3f6cded363c
{
    "code" : -32600,
    "message" : "No information available about transaction"
}

**Comment by AlexiaChen** [comment]
应该就是那天说的缓存刷盘的问题了。经以上描述的现象，感觉一致，而且如今没有复现出来了。
