### ISSUE TITLE
分叉回滚时未设置找零花销（txView.SetSpent(CTxOutPoint(txid, 1), spent0);）（严重BUG）

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#154]
函数CTxPool::SynchronizeBlockChain中：
uint256 spent0, spent1;

txView.GetSpent(CTxOutPoint(txid, 0), spent0);
txView.GetSpent(CTxOutPoint(txid, 1), spent1);
if (AddNew(txView, txid, tx, update.hashFork, update.nLastBlockHeight, index) == OK)
{
	if (spent0 != 0)
		txView.SetSpent(CTxOutPoint(txid, 0), spent0);
	if (spent1 != 0)
		txView.SetSpent(CTxOutPoint(txid, 1), spent0);

	change.mapTxUpdate.insert(make_pair(txid, -1));
}

txView.SetSpent(CTxOutPoint(txid, 1), spent0);这句中未设置spent1，导致找零未被设置为花销状态。
应该为：txView.SetSpent(CTxOutPoint(txid, 1), spent1);

**Comment by sunhantao** [comment]
的确有这个问题😄，issue结束后请关闭
