### ISSUE TITLE
出块时出现双花现象（偶现）

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#168]
出块时，提取的交易池中的交易，存在找不到前序UTXO，导致出块较验失败。
通过gettransaction查询出现问题的交易，及前序交易，都存在，并且前序交易已打包在块中，所以怀疑unspentdb的数据存在问题，即与TX数据不同步。
存在几个节点都是这样的现象，但每个节点出现问题的交易不同，并且几个节点都停留在同一高度不前进。
当一个节点重启后，该节点能出块，并能将块同步给其它节点，其它节点可以继续同步和出块。
出现问题的日志及查询记录如下：
2019-10-18 02:06:43.893511 : [bigbang] <info> {blockmaker} - <blockchain>AddNewBlock Get txContxt Error([4] missing previous) : 5da86898c2d3600b0775fe4c085aa781d1e71e5a6dd7535a153abea31a7e23a8 
2019-10-18 02:06:43.893536 : [bigbang] <error> {blockmaker} - <blockmaker>Dispatch new block failed (4) : missing previous

bigbang> gettransaction 5da86898c2d3600b0775fe4c085aa781d1e71e5a6dd7535a153abea31a7e23a8
{
    "transaction" : {
        "txid" : "5da86898c2d3600b0775fe4c085aa781d1e71e5a6dd7535a153abea31a7e23a8",
        "version" : 1,
        "type" : "certification",
        "time" : 1571317912,
        "lockuntil" : 0,
        "anchor" : "69ed2d6ebb9ace57ca0c1e6eaa4d8eaa2db458bfaa37b37d1a9bfcec46ef099e",
        "vin" : [
            {
                "txid" : "5da83e259c7550fd00b2e6c13191d84c7e0a10cae77e432dd7bd8c7129d1831b",
                "vout" : 0
            }
        ],
        "sendto" : "20m053vhn4ygv9m8pzhevnjvtgbbqhgs66qv31ez39v9xbxvk0ynhfzer",
        "amount" : 100.000000,
        "txfee" : 0.000000,
        "data" : "f2ae3f94e7e45b5eeed22e6a6067859abf70d12472b6cfd2d9f7bd9a143545b732000000000000001076f5c337cfbc49469db8b873a707b967668068f87a46ff58e6bc9bec742eae4aa1c2faca9ab1d98b112afd915b89ce41fac0672b6bf6b4a06e18550358715c267d8dc92c60fc73d109a73a0c35e5473c4ca2c00298eb0f641d16571b38864744913e5aca514c1236068df9a298ba13f5bb2822f93506740edff7241a0cd4c92111bfe1d443764facb0474b6b88470b7eb2e8195e13c3a1212bd16111ffbb3adfe37fc908c561dfaf4e7ed451ade42b3461f5c11d72e3b7c842801445b37966e6d208a27aa2ba34df858469d67f2e168c8c336935714447e9a28a2c321bfeec36dfadde8ca1d4e2793ee590f7d54f37bd76506afe5e0312658654be14a7c7c96906c659165cc1e12bc2b90befb430589c56b017ba123a340a4a6dea93278b862ea6f5a9cdfd1d8cf36fb6cfe1d5595e6a9680e4868ab1f6b1a83f08a10c3d748e7785eb019cec5fae18eb331f42db5756299630c5431f345163830701b1c0bba833fceacff7feb84636242cafde278f9cd1b9678dd9229a77199e8d12ed678aae49880bbbc43a3da32097c785efb59111a8d3c9cc9bab85cde82533d727997ad42b29b86262264c857287609f845ecd8be55417b82a9eab5e5ff4db1d3d86b6f0978dcbae8146f7c9de08f409bf894cea0fa1a2cac43ec610e1ca669d2c6fbec11ca469eb883288cb5234547750715f5faf072051c9bc8621a9b1f0ec372eda6f6a6a8258666e6a95ce73dd92370ad6b625e3f05786a981ab7b55af771616eeea398485d691360356b72f0ca7c76082f2478ab848683a6d63a33cb4c0ae53b8c2f65ac25906c9c73db32f064ce5806eb16c2ac85628d0f977cd6b966a61f7c2179b4a031ae792bb459c0eeb58466b5a4683939f39ab6e8958c27de575633f7b8cfe91dba85b1f1c1d5f2d4f8684bc4a2cec2dbaf6fa17646d22a3229c868d2de1d72ff2f6f17676a9d4e5f1d8b054d39fcb115ec435d5228ef1bea9bd39dcb8713aa79f7b6d3e23df7fc7c5193762b662beea5d56b5036b49ee60d1f3e234e13cc100f2340e5541cc2c5f2d5367915e1a962b8bbc202a500b8a6445b7b3864959af6418adaede7c402f678ead97967fef27dabba2f4b48af4d47be93bd22afe40a765b646e2de80fdb5238a360b49cbd43e819b329032d5ea719006dd0483e93c47ff03f8775f8373701f652150d7a7160294d8936e0b880284d2651ebb4f99f3a4f2f3c58ce016d5dd9712ca245685cd8d3fe7deec0167cde4d597a5811e68733f501956463c1c42a45a3bd1d1636633c3c604f4fd3a166588a64d5e7dd4fab17329d7c2bd6cd272f5fdb4da3391b63ac89fe5eb5ace990f029745b1295901afdc49b05e9adcc90f91a94f379679533ed04ac24db9ab03af4eb4eeaff78feb481b7902a209740dce667c1565cff086f997c0f1a7ac59aab15f6922369988dc4e743f4fca2ea7b079ff4c6c2db70c4eee0ec89a6247e75b0caed6cc4ded0775fc13e537be600386f2a9b0efde7210d62e7306f40c168135f3531fa89d73fb3726b6b270f06272bdba77bf158aeeb581b32531dfc8dba4f2eeef2946bc655a167fbb464ea7d9bdd729ae390a42a95f8156eb6fb1e9cda45540565e2335148edaf7f8b157e1cb1ac59bebdcbbcbea4b223c6812ac841f49c8d934cf8629433ffc5501749ed60a31658b01484b93ef91b1bdf752ae29473990c5e116a37d73852ee697d3e946ceca54aa11e338b2815a2ba6e6db7123b27f23e9bc7c32cfd5cde14905a203f0b396dc53b482ea30389f1223389e88bc764e1b3a45241055ceef0fd8f14e766323b3469cf2bcadd5e51f1e21f6f58724b2a1fc8c367cff326df20a3ed3d6e9900bc91f6792a4ca96edec20fcb7fab8f0f7a213ec1b8d2924b9090c51385ee794719df848a1c6615dce3c0bd34c1a201429d88ab29b35b124b0405def07a13c692c2060357c3648c6e70fe729e6650b8b21c707ca34661c06c5dca7a5d949657abee0a1eac2879e12e96bc7f1a61c3817c1c363c422c13b9b3d877e22a2ea2cf16a5a47e30836881c98df4039710bdb200a778c17494178ec351ab0e6940ca8e059e1b881787d8ec7216202dcf3f8007a89a02ded695853da243718506c1e06a4fbe2051a3985f42e86b676f9f136517cf0b3e271b681881278cfd58f97c14c2690e370552a34bf75be9ee83dbfc1b0859524f9f218a038302d4d43689a15ea6354696b6045056503aef6ecfd7d0e8766670563074c18d2ee4f85facbae4f2db3afc43bc995ada97785709f22a9f04d548b462363cfc90b46af506614114a81fcdf8e300c5da4b91daffda3296223c68a9bb57d6794bb1c7b079e07",
        "sig" : "02050051ee3527a1b4d116fc5dbacb7a82d778c32635f630bbe34ed3d5f77307ab17b24437dafecb9c83cb9f8bbe60c43acf42eebcb69c1525e6f84077fb293f880191ba8db6735d7ae45f92841eaaa588a23f1a3be785076fd737ec1911bbd8e75768ea2686d63560000022fc5fcc2a4ee7c8e495d267b33fd474b91be187a8d3a73dc843cfe76ea44e57e41ade652ec64da96fa5aafff0e2dcc69aa20d29c94e0f",
        "fork" : "69ed2d6ebb9ace57ca0c1e6eaa4d8eaa2db458bfaa37b37d1a9bfcec46ef099e",
        "confirmations" : 0
    }
}
bigbang> gettransaction 5da83e259c7550fd00b2e6c13191d84c7e0a10cae77e432dd7bd8c7129d1831b
{
    "transaction" : {
        "txid" : "5da83e259c7550fd00b2e6c13191d84c7e0a10cae77e432dd7bd8c7129d1831b",
        "version" : 1,
        "type" : "certification",
        "time" : 1571307045,
        "lockuntil" : 0,
        "anchor" : "69ed2d6ebb9ace57ca0c1e6eaa4d8eaa2db458bfaa37b37d1a9bfcec46ef099e",
        "vin" : [
            {
                "txid" : "5da83cc17370a4c9cd19b726a5bb37ba6f4b45bf271b5b8769e3347fd70e2cdc",
                "vout" : 0
            }
        ],
        "sendto" : "20m053vhn4ygv9m8pzhevnjvtgbbqhgs66qv31ez39v9xbxvk0ynhfzer",
        "amount" : 100.000000,
        "txfee" : 0.000000,
        "data" : "55c3e4a30a6903b6bc3a1dd9a44367757d5e520769ede745a1757d4c00af3dd53200000000000000e706e9e674af0a33f3b19bc15f3e70723685cb5e2dc7086e91456ee9ba4efdf9b947ccc58022330870f11c2cd5ebc884587f9686d16722c07c4d937c1818e442735a78de8acba8c09b92725480bf4dcf09823313f0fe500cd678fea2f62f26f9dc92445faefa65c5e7dde9ecdefc45d7219ccd1df96a39d6b1d5c5612471ba189dd0af45f07dd633b32c918b69f92e326a5c3c1d2af5e590656e84418d20a1b0f270c62f3cc6b6d20f5d18ce505df5b2bd4b64b238506767d5d5822b81a55d5ccd1c86bcd2bd89266bff35307781ebe907677fa0404ba0c99edb148bf29564edd22ff2adf7b9f2b91569fb32ebb68769d0d6cfb70f59c20348502589787ff1700e84a2534fa1f0cee16107322cf5bcb655d5805b276d7928e2fc03c5e7fa0a1ffa8a475bf47855f331f8218bd25ab52bfb9a4e2cc05d556012d788ba61f6f330cd5c902d60b87ec0a3dbe7028a699b773fcd3406619eb2bef52eefd4d3ed7741b3a22cb066bd623351c626dab26e5c186cbe67ada38cb5aa14c46553d3c536a5e231cfb8fd4baf0cb1945c964070ab76b4a750d8fa48f33eb7d5d75c55b52012a810e0ac5e52d3c76b47ed05fcacf5a8f3b7f166a33d60f48462392df5b29b4aba975553fc3ce059f170a391654960f8d616654e8931addb6858b06128772da9d5b4f59802ae44c033366ca0983048f6f4aa8f15e49e0f123219d366038c1ab0fcc416933ef7caf0c4a6066944173ff111e52cc4a2eeff51177d10d7cac14a71d0e7f7e67990e383a5b799fe85f91f96025a678c3011009ae25dabee5f817bc8bf0c0f1cee5afda47a3fe82cac2b0b81ddf33f6df1f1c1fb89facbaf973eaaa7c794c8407fdc29d7fac7289015686635ae6a45b0cace395948d8c05f1d79da71e75e12c5a5631c86f123b378b7d12ece1d860d68707349b9cefedfceafa75453b1049290392d6d291948c002cdf9d540333fba502535ee367546dab6b0e8d68c1d17ba9492f1abd0753a71e338cd9bbd74d1a55023b27cae5c8d2e9d5990e3370f981540df451764f7da711c2b42efe7f494cc86a39f83eef464dd06c3f1492c141fec0084ff4412e96397a386f0a0200d42033af9aab46ccad16b5c5aa0b6589c89a1145baf9330d315b697d71cf22da69d964ca91fbf5123f1634770f5f88cd34c2baca72b704b89d14aecf42a85cce574b17bcbf7328c0098c6c885741a66ae22d18b61cf8c68d9019658152f89e775152be863ee78b66a7fc1cc214bc384dfd3118c223e4a39cbb1ee490e02617f2a966c6892d3e8f4db50fc8207a1f0fcb7205246bd32d33b9adbb55f88ab60b43cca1d2c5c289e27d11a72835e4fe20854542d65c927ab3ceb7f2af293070a14d30a6d47ef60a0bfafa2e6e5d9138f5016a8456de671a405097341bf446a384dde96bd6eb46973891f00489c0fb47a578cbdc92ea1640f46346cd9ba0feec6ee9818b1d59955fc03797d98dd6d2378717cc2c2dc10df939447a7dcc934ee74eab7268efa8ac253adb09e6e811e0e96e013e0d05ced249623292c1cf11a8d9d067ce7b48d4bdd0381ef2314f4dc74590d4c7adacf1a8c33069559f88c3aadb70b0413fb9a8946694f8bb716af03cca43c47318d6e5892ac095d4dfa992d3b7c666d80276505c0f7ad2348609d34cff1bd2678005ebdf4b91efeedf51d89bf5dff0465650cb856ba13082ee7e7eacf046cb37f553021d41cb705188e74322997bf7ba17810fc4400d2ba29551abda1d4aa14de24d52db475aafbb67a57ede377650f5edff181f543afdbdca1576ebb8cdb6d700e3f22c186f4bb42c55544508271145a125690e3050deaa33d6d3f70305e6c329cfac81a24e6496e75c52290085c6927c38881645d1861b8b08579f806734e78fe7e6e3984bc0f276fb67e1b2a984ed0f034763b649f8f2cdc22499e6e0e05cd916724d68483b4ec01bb880a59943d5589cc99dcd75840d7eebab12931fb14327e9da3eedd606e74b2fca9d806c86c3d4ab855204674373a94b1bb1e93eb6b22a40e2a751c0cb76263fc8b44f3738eb1c62c81ee14a64110fbfcfe8189cd39d1344ab1c0952fdff6d61ef582527946063103e2b0277e0a2f22d374cd2374b605f202cb64db7a9a9411e360e69d123888ea162bc78704bf6600eeb654d826e707b642c3831c19a70408aae9d739691d01b54ff9b5ca11b8422c8bcc1791f2031f6c42d57a4517246b0ae75d8c01a35a35e345faaaf158b6842360dae2d4ba23fc2028d78c0d1c0993c3767a11a3093087c041da8a5e17c93e96d56a1d9ee3cee55261b4fd1bc8e358c4cf833ac1af19f4a2fccf9942c2c171e83081977601",
        "sig" : "02050051ee3527a1b4d116fc5dbacb7a82d778c32635f630bbe34ed3d5f77307ab17b24437dafecb9c83cb9f8bbe60c43acf42eebcb69c1525e6f84077fb293f880191ba8db6735d7ae45f92841eaaa588a23f1a3be785076fd737ec1911bbd8e75791a5b58eed153090857d055d8f909cf973da5f3648ba0c7552bed89c19fa30d6e1014db666dac074a99043f4e27db2515ff7cb2c49f684d6c4e6197e5ec5ba01",
        "fork" : "69ed2d6ebb9ace57ca0c1e6eaa4d8eaa2db458bfaa37b37d1a9bfcec46ef099e",
        "confirmations" : 4
    }
}

bigbang> getblockhash 27869
[
    "afe88a1381e9b4a276813de04a733411d7c4da1d75f20bf3517bfac1b1e06034"
]
bigbang> getblock afe88a1381e9b4a276813de04a733411d7c4da1d75f20bf3517bfac1b1e06034
{
    "hash" : "afe88a1381e9b4a276813de04a733411d7c4da1d75f20bf3517bfac1b1e06034",
    "hashPrev" : "81adbb83dda8c2e9bfb5a5171916bac7499aeb095290f111f7a642a4ed47e698",
    "version" : 1,
    "type" : "primary-pow",
    "time" : 1571317703,
    "fork" : "69ed2d6ebb9ace57ca0c1e6eaa4d8eaa2db458bfaa37b37d1a9bfcec46ef099e",
    "height" : 27869,
    "txmint" : "5da867c738e18ef79053d8608b47a6fefff8cf3ad582c5755bc34f665987c662",
    "tx" : [
        "5da83e259c7550fd00b2e6c13191d84c7e0a10cae77e432dd7bd8c7129d1831b",
        "5da83e256cfda5edac5a4c3f019ac15cb752f12e7b0bd990bb3122c74f497b39",
        "5da83e260cb42a4ab6bf71aa83b0f59516b58c3d2442a69fd28a57cedea92a1d",
        "5da83e25cc4ed5d9020e1f5dc418544691224843e8db39d12b63df53663f9e5f",
        "5da86784a54c420873b2dcc32268df404f4a8cd24081080438a26959c273eab0",
        "5da86785bf33ad86fbf63a3553a21ec327709b33814a1559ea75e98d0dff9c8f"
    ],
    "prev" : "81adbb83dda8c2e9bfb5a5171916bac7499aeb095290f111f7a642a4ed47e698"
}

**Comment by AlexiaChen** [comment]
@cch809094 @sunhantao   这个issue是很早的时候提出来的，我看描述，与现在的现象一样。其实很早就发现了。
