### ISSUE TITLE
NetChannel业务机制改造

### ISSUE THREAD

**Issue by AlexiaChen** [bigbangcore/BigBang#206]
- [x] GetBlocks的Locator方案需要几乎照抄BTC的方案，不然长短链切换的时候，本团队几个人的讨论方案都会有问题。
- [x] 测试该方案同步仓库master链，同步自身的链成功

**Comment by AlexiaChen** [comment]
参考BTC全节点 golang版实现（golang版为BTC社区核心人员实现），思想，算法几乎保持一致：
- https://github.com/btcsuite/btcd/blob/master/blockchain/chainview.go blockLocator（GetLocator的处理，step=2^n）
- https://github.com/btcsuite/btcd/blob/master/server.go OnGetBlocks （处理GetBlocks的Locator表）
- https://github.com/btcsuite/btcd/blob/master/blockchain/chain.go locateInventory（真正处理Locator向量的逻辑在这里）
- https://github.com/btcsuite/btcd/blob/master/server.go OnInv （处理Inv消息,主要是压入Inv的Channel中，异步gorotinue处理Inv，这里的Inv是包含了Inv向量列表的）
- https://github.com/btcsuite/btcd/blob/master/netsync/manager.go handleInvMsg (异步处理Inv的实际Handler)
说下大致思想吧， GetLocator的思想与Bigbang差不多，对端peer处理GetBlocks消息的思想也差不多
都是找到最近有的Locator点定位的Block，然后把这个Block的下一个Block作为start，批量Get出来（这里的最大数量是500，Bigbang是128），包装成Inv向量列表，回复给请求端。请求端根据回复的Inv列表找到列表中最后一个Block的Hash，根据这个Hash再次往上索引添加Locator列表，这个样Locator向量就可能会更新了，不会导致Locator向量一直不变，导致重复请求相同的Inv列表，同步Block的bug就解决了

**Comment by cchanm** [comment]
当前测试bigbang的深分叉和静态节点的块同步都没有问题。

**Comment by AlexiaChen** [comment]
@cch809094  现在不是测试，是理论上就有问题。这个理论上的问题，是在一个新的特殊场景下出现的。

**Comment by sunhantao** [comment]
当前bigbang的两种方法都有弊端，BTC的思想是后续的locator一定是对端那条链的locator，而我们的都是原本自身长链的locator。比如说A节点长链1000，B节点拥有A节点的那条长链的700高度，并从500高度分叉一条长链。假如A给B的inv是1000长链的[400 - 600]，B节点将判断inv存在，并继续将自己那条500分叉链的locator继续下去，哪种locator都是错误的，永远无法同步到1000那条长链。

**Comment by cchanm** [comment]
这种情景当前bigbangv1.0中已支持的，并经过测试可以同步的，当前代码能支持高、中、低分叉深度的同步，并且支持分叉临时变更的情况同步，当前是128的INV数量，最大限度的减小了同步浪费，以及减小BLOCK数据的缓存，128的设计也是减小内存攻击；当前bigbangv1.0是从最新块按127间隔向前查找分叉点，查找重复的块数较小，最大126个块是重复，而BTC是采用2的幂次方为间隔，查找 重复块的数量比较大；
由于我们的链的块数比BTC大很多，BTC每年5.2万块，我们链主链每年52万块，支链每年1500万块，按2的幂次方作为间隔，查找重复块的量可能非常大，由于BTC的块数不大，可以按这种方式做，但按种做法，不适合我们的链。

**Comment by AlexiaChen** [comment]
@cch809094   反过来想一下，其实你这套逻辑BTC可以采用，并且BTC的块更少，按理来说，复用你的逻辑BTC Locator性能应该会更好，那为什么他们没想到这个方案呢？BTC用2的n次也会查找重复的块的量比较大，即使当下够用就好，也为什么不采用更优的呢？

**Comment by AlexiaChen** [comment]
@cch809094   这么说吧，BTC这套逻辑就是获取对端Peer当下最长的长链作为更新本端的Locator。你的逻辑是否支持呢？你的貌似是被动添加对端Peer的长链块，但是Locator并不更新，等超过了再更新Locator。或者你的代码又有更新了？
