### ISSUE TITLE
Remove Peer(3 : RESPONSE_FAILURE) GETDATA超时无应答的问题

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#213]
节点之间存在Remove Peer (3 : RESPONSE_FAILURE)日志，即发送GETDATA后，超时没有收到相应的应答消息，则认为超时，并断开连接。
测试发现两个节点通过127.0.0.1连接，也存在该日志，并且两个节点的网络质量比较好的情况下，也存在该日志。
测试程序已增加了查询失败返回GETFAIL消息功能，并且查询两个节点都无查询失败的日志。

日志如下：
2019-10-29 07:11:18.963198 : [CPeerNet] <debug> {peernet} - Remove Peer (3 : RESPONSE_FAILURE) : 127.0.0.1:9901

2019-10-29 07:25:29.367541 : [CPeerNet] <debug> {peernet} - Remove Peer (3 : RESPONSE_FAILURE) : 18.138.93.175:9901

**Comment by shangqd** [comment]
发送的GetData对端收到了吗？

**Comment by cchanm** [comment]
是由于NetChannel线程被阻塞的原因：同步过来的块数据时，调用CBlockChain::AddNewBlock函数中的view.ToString()函数阻塞了，导致NetChannel线程被阻塞，不能处理请求，导致对端超时。

以下为测试的代码及查看的日志：
1）测试修改的代码：
    Log("AddNew Block : %s\n", pIndexNew->ToString().c_str());
    if (Config()->fDebug)
    {
        StdLog("Peer3Test", "AddNewBlock: 11111111111111111111111111111111");
        std::set<uint256> txUpdate;
        view.GetTxUpdated(txUpdate);
        StdLog("Peer3Test", "AddNewBlock: 22222222222222222222222222222222");
        std::string strView = view.ToString().c_str();
        StdLog("Peer3Test", "AddNewBlock: 33333333333333333333333333333333");
        Debug("New Block %s tx : %s\n", hash.ToString().c_str(), strView.c_str());
        //Debug("New Block %s tx : %s\n", hash.ToString().c_str(), view.ToString().c_str());
        //Debug("New Block %s txUpdate size : %ld\n", hash.ToString().c_str(), txUpdate.size());
        StdLog("Peer3Test", "AddNewBlock: 44444444444444444444444444444444");
    }

2）日志信息：
![image](https://user-images.githubusercontent.com/45554027/67936156-3aeb1900-fc06-11e9-9ada-f9a96a38c9b8.png)
