### ISSUE TITLE
存在僵尸节点的问题

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#214]
通过listpeer查询节点列表时，有些节点长时间存在，但lastrecv参数值没有变化，并且与lastsend值差距较大，该IP主机上已查实没有进程运行。与查询的其它节点对比，高度也差距较大。

listpeer查询信息：
    {
        "address" : "18.138.93.175:9901",
        "services" : "0000000000000003",
        "lastsend" : 1572333731,
        "lastrecv" : 1572333760,
        "conntime" : 1572331827,
        "pingtime" : 0,
        "version" : "0.1.0",
        "subver" : "/Bigbang:0.9.2/Protocol:0.1.0/005ec11ab6d7f972fbc6ae1e21aebcff8d181626",
        "inbound" : false,
        "height" : 2103,
        "banscore" : -10
    },
    {
        "address" : "222.212.171.203:42229",
        "services" : "0000000000000003",
        "lastsend" : 1572333674,
        "lastrecv" : 1572332888,
        "conntime" : 1572332603,
        "pingtime" : 607,
        "version" : "0.1.0",
        "subver" : "/Bigbang:0.9.2/Protocol:0.1.0/005ec11ab6d7f972fbc6ae1e21aebcff8d181626",
        "inbound" : true,
        "height" : 1399,
        "banscore" : 4
    }

**Comment by sunhantao** [comment]
Ping Pong机制需要后续处理

**Comment by AlexiaChen** [comment]
@cch809094   这个问题是否已经解决，解决完了，我就关闭issue了。
