### ISSUE TITLE
发布新版本注意事项

### ISSUE THREAD

**Issue by shangqd** [bigbangcore/BigBang#218]

**Comment by shangqd** [comment]
修改时间戳为项目启动时候的时间戳，增加安全性防止第三方攻击

**Comment by sunhantao** [comment]
pow-3month分支合并到master后，在master打v1.0.0的tag

**Comment by shangqd** [comment]
#define MAINNET_MAGICNUM 0xd5f97d23
#define TESTNET_MAGICNUM 0xef93a7b2
这两个值修改下，不修改可能会与其他的链出现重复

**Comment by erzaxs** [comment]
发布新版本release notes可以写详细点么，比如RPC变更细节、破坏性改动、非兼容改动等等，最好可以在源码目录下加个CHANGELOG文件
