### ISSUE TITLE
大回滚时出现钱包里的地址的余额变大的问题

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#262]
长链吃短链时，短链中有挖矿模板地址有TOKEN，长链和短链都是从创世块开始分叉，两条链合并后，理论应该短链的模板地址的TOKEN为0，但合并后，短链的模板地址的余额比较大。

复现条件：
- 尽量用48的数据
- 短链要不停的产生交易

这样这个bug复现的概率才会加大。

**Comment by AlexiaChen** [comment]
补充下一个验证结果：
用一个新的空数据的节点同步，并导入挖矿模板到钱包中，同步数据，发现模板地址的余额为0

**Comment by AlexiaChen** [comment]
测试进展：

用
[48-testnet.tar.gz](https://github.com/bigbangcore/BigBang/files/3850831/48-testnet.tar.gz)

川华备份的48数据的长链覆盖这边挖矿模板有余额的短链，长链吃了短链完成以后，再次查看balance，余额正常，变成了0。也就是，issue描述复现不出来，不好复现。

截图（短链被覆盖之前），余额14989
![2019-11-15-175128_765x328_scrot](https://user-images.githubusercontent.com/8574915/68933928-a0c3cd00-07d0-11ea-8c7f-dd3511b11df9.png)


截图（短链被覆盖以后），余额为0：
![2019-11-15-175005_692x294_scrot](https://user-images.githubusercontent.com/8574915/68933819-6eb26b00-07d0-11ea-8dea-10250bb869c0.png)
