### ISSUE TITLE
测试两个节点时出多种不可用的情况

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#3]
测试方法：
1）通过bigluashell启动两个节点，为每个节点投票1.4亿TOKEN（总TOKEN为3亿）；
2）创建10个分支；
3）启动三个RPC压力测试程序；
4）程序DPOS共识协商块高度为原参数（15，30），未修改这个；

现象：
1）有时POW阶段就有问题，无法使用RPC客户端查询信息，不再产生日志；
2）有时在出几个DPOS块后出现问题，无法使用RPC客户端查询信息，不再产生日志；
3）查看日志文件，存在[WARN]  Remove Peer (3) : 127.0.0.1日志。
4）有时RPC能查询，但节点与节点之间的连接断开，并且长时间不能连接；
5）有时RPC能查询，listpeer在两个节点上都能查询到连接，但不同步TX数，两个节点的高度也不一样，gettxpool查询两个节点，TX池的记录数也不一样；

**Comment by AlexiaChen** [comment]
改了DPoS规则以后，有比较大的改动。不能发现上述情况。到时候发现问题重新梳理，现在暂时关闭。
