### ISSUE TITLE
获得源码：WINDOW BUILD 出现链接失败

### ISSUE THREAD

**Issue by thomas5396** [bigbangcore/BigBang#307]
[https://github.com/bigbangcore/BigBang/wiki/Source-Installation](url)

git clone https://github.com/bigbangcore/BigBang.git
cd BigBang
mkdir build
cd build
cmake ..
make bigbang
cd src/bigbang
./bigbang help

-最后一步骤 ./bigbang help 出现链接失败(Connect Failed)
有没有决解方案

**Comment by AlexiaChen** [comment]
Could you write more details about this issue?

**Comment by chajiubu** [comment]
If you run bigbang on windows,use "bigbang help"  instead of "./bigbang help",please.
