### ISSUE TITLE
连不上节点

### ISSUE THREAD

**Issue by rlinxy** [bigbangcore/BigBang#308]
getpeercount 返回一直是0
另外
addgroup=e96f1d8ec9bdc8e3b56a992f183d5c384603edabe655e4e839fdee9ec57b2abf # genesis fork in test network, please change genesis if you are in real network
请问去哪里找主网的genesis？
谢谢

**Comment by AlexiaChen** [comment]
go and access BBC explorer http://www.bbcexplorer.com/home/00000000b0a9be545f022309e148894d1e1c853ccac3ef04cb6f5e5c70f41a70

you will see the genesis hash

**Comment by rlinxy** [comment]
solved by removed testnet and add a line as below in the conf file
dnseed=15.188.165.143
