### ISSUE TITLE
dnseed in configuration file

### ISSUE THREAD

**Issue by bgeraghty** [bigbangcore/BigBang#309]
Hello, I apologize for not speaking Chinese fluently so I must use English.

In the configuration file of the bigbang-server (bigbang.conf) I am not sure what the configuration setting "dnseed" is used for, and what IP address should be put there?  If someone could explain this it would be greatly appreciated, so that I can start using and testing this software.

Thank You!

**Comment by AlexiaChen** [comment]
dnseed config item is used for connecting dnseed server to lookup others P2P bigbang-core nodes, this item you should put 15.188.165.143 like as follows:

```ini
dnseed=15.188.165.143
```
