### ISSUE TITLE
请问怎么关闭钱包节点挖矿

### ISSUE THREAD

**Issue by rlinxy** [bigbangcore/BigBang#311]
按教程搭了矿池，但是钱包节点看起来一直在挖矿，占了服务器很多CPU资源
谢谢

**Comment by rlinxy** [comment]
试了半天没结果。。。求教

**Comment by sunhantao** [comment]
bigbang.conf里面不要设置cryptonightaddress和cryptonightkey

**Comment by rlinxy** [comment]
谢谢，已解决
