### ISSUE TITLE
非正常关闭程序导致获取交易失败

### ISSUE THREAD

**Issue by ouyun** [bigbangcore/BigBang#323]
bigbang 在非正常情况下关闭时，获取区块信息正常，但其中的交易获取失败，使用信号9去关闭可复现这个问题

**Comment by AlexiaChen** [comment]
@ouyun  能再详细点吗？ 获取区块信息(getblock)正常，但是其中的奖励交易(gettransaction)失败，这个区块的前提条件是最新的打包区块，而不是以前的区块，这个是听 @shangqd 描述的。是否是这样？  我再在issue里文字确认下。

############# update ###############

并不是最新块的mint Tx没有，前序的块的mint tx也没有。查找TxIndex失败，就说明数据根本没落盘，而是正常关闭才落盘

**Comment by AlexiaChen** [comment]
确实是最新块被kill -9以后，其中的mint tx通过查找失败的概率加大，然后错误是从dbBlock中RetrieveTxIndex中失败，Index失败了，就不往下面走了，查找完成Index时候，才会去tsBlock中的.dat块文件里读取相关Tx的详细数据

```cpp
bool CBlockBase::RetrieveTx(const uint256& txid, CTransaction& tx)
{
    tx.SetNull();
    uint256 hashFork;
    CTxIndex txIndex;
    if (!dbBlock.RetrieveTxIndex(txid, txIndex, hashFork))
    {
       // 是这条日志打印出来并返回了
 StdTrace("[BlockBase][TRACE]", "RetrieveTx::RetrieveTxIndex %s tx failed", txid.ToString().c_str());
        return false;
    }

    if (!tsBlock.Read(tx, txIndex.nFile, txIndex.nOffset))
    {
        StdTrace("[BlockBase][TRACE]", "RetrieveTx::Read %s tx failed", txid.ToString().c_str());
        return false;
    }
    return true;
}
```

其实本质就是数据不一致导致的，如果不是掉电或者强制被kill -9以后

**Comment by AlexiaChen** [comment]
调研了下，数据库一般都有类似的功能，有个比较复杂的机制叫Write-ahead log（WAL），就是预写日志，预写日志，就是先把变化的数据写到WAL日志文件中，然后commit的时候再根据WAL日志把数据写入实际的文件中。防止掉电，崩溃，被强制kill -9的文件数据不一致的情况发生。

具体步骤在该问题下有回复：
https://stackoverflow.com/questions/30181264/write-file-data-consistency-in-practice

WAL概念介绍:
https://www.jianshu.com/p/a37ceed648a8

**Comment by AlexiaChen** [comment]
找到了一个C写的WAL库，但是运行最简单的单元测试，崩溃了 https://github.com/yinqiwen/swal
