### ISSUE TITLE
V1.0.1版本经常出现节点停止同步

### ISSUE THREAD

**Issue by rlinxy** [bigbangcore/BigBang#324]
跑着跑着就停了，不停重复
CPeerNet:warn|peernet|Remove Peer (5 : DDOS_ATTACK)
CPeerNet:warn|peernet|Remove Peer (5 : DDOS_ATTACK) 

部分log如下

> 10:07:18.208358|CPeerNet:warn|peernet|Remove Peer (5 : DDOS_ATTACK) : 18.139.37.48:9901
10:07:18.208409|CNodeManager:info|peernet|Dismiss: Add idle node, peer: 18.139.37.48:9901, nRetries: 3, interval time: 240 s
10:07:18.208441|CNodeManager:info|peernet|Ban: erase idle node, peer: 18.139.37.48:9901
10:07:18.208478|CNodeManager:info|peernet|Ban: Add idle node, peer: 18.139.37.48:9901, interval time: 640 s
10:07:18.208561|NetChannel:info|netchannel-even|CEventPeerDeactive: peer: 18.139.37.48:9901
10:07:41.766041|CNodeManager:info|peernet|Employ node, peer: 52.220.118.211:9901
10:07:41.766178|CPeerNet:info|peernet|Start connecting peer, peer: 52.220.118.211:9901
10:07:41.843457|CPeerNet:info|peernet|Connect peer success, peer: 52.220.118.211:9901
10:07:41.843593|CPeerNet:info|peernet|Add New Peer : peer nonce: -911168357731892256, address: 52.220.118.211:9901
10:07:41.920761|NetChannel:info|netchannel-even|CEventPeerActive: peer: 52.220.118.211:9901
10:07:41.921961|NetChannel:info|netchannel-even|DispatchGetBlocksEvent: Peer: 52.220.118.211:9901, nLocatorInvHeight: -1, hashInvBlock: 0000000000000000000000000000000000000000000000000000000000000000, hashFork: 00000000b0a9be545f022309e148894d1e1c853ccac3ef04cb6f5e5c70f41a70.
10:07:42.430153|bigbang:info|netchannel-even|<blockchain>GetTxContxt: RetrieveUnspent fail, prevout: [0]:5ded5378cd88cba14e6360541f81b688605d4cbe63c4c34dfa32d9c4e9c23180
10:07:42.430230|bigbang:info|netchannel-even|<blockchain>AddNewBlock Get txContxt Error([4] missing previous) : 5ded569f85230b5c58c9e832ac7f435db65a1c3c297d9470f74eeafe07f55481
10:07:42.430281|NetChannel:info|netchannel-even|NetChannel AddNewBlock fail, peer: 52.220.118.211:9901, block: 00003564afbe1fc613be174cc326e314741df725cf15fce44dc9002f941aefab, err: [4] missing previous
10:07:42.430321|NetChannel:info|netchannel-even|DispatchMisbehaveEvent : PostAddNew
10:07:42.430388|CPeerNet:warn|peernet|Remove Peer (5 : DDOS_ATTACK) : 52.220.118.211:9901
10:07:42.430447|CNodeManager:info|peernet|Dismiss: Add idle node, peer: 52.220.118.211:9901, nRetries: 3, interval time: 240 s
10:07:42.430483|CNodeManager:info|peernet|Ban: erase idle node, peer: 52.220.118.211:9901
10:07:42.430508|CNodeManager:info|peernet|Ban: Add idle node, peer: 52.220.118.211:9901, interval time: 640 s
10:07:42.430595|NetChannel:info|netchannel-even|CEventPeerDeactive: peer: 52.220.118.211:9901
10:09:01.766031|CNodeManager:info|peernet|Employ node, peer: 15.188.165.143:9906
10:09:01.766146|CPeerNet:info|peernet|Start connecting peer, peer: 15.188.165.143:9906
10:09:01.985342|CPeerNet:info|peernet|Connect peer success, peer: 15.188.165.143:9906
10:09:01.985486|CPeerNet:info|peernet|Add New Peer : peer nonce: -6547599354710650491, address: 15.188.165.143:9906
10:09:02.766040|CNodeManager:info|peernet|Employ node, peer: 15.188.165.143:9901
10:09:02.766107|CNodeManager:info|peernet|Dismiss: Add idle node by reset, peer: 15.188.165.143:9901, interval time: 30 s
10:09:04.194263|CPeerNet:warn|peernet|Remove Peer (2 : NETWORK_ERROR) : 15.188.165.143:9906
10:09:04.194337|CNodeManager:info|peernet|Dismiss: Add idle node by dnseed, peer: 15.188.165.143:9906, nRetries: 6, interval time: 1920 s
10:09:04.194371|CNodeManager:info|peernet|Ban: erase idle node, peer: 15.188.165.143:9901
10:09:04.194409|CNodeManager:info|peernet|Ban: Add idle node, peer: 15.188.165.143:9901, interval time: 320 s
10:09:04.194459|NetChannel:info|netchannel-even|CEventPeerDeactive: peer: 0.0.0.0

**Comment by rlinxy** [comment]
重启节点也一样卡在这。不得已暂时似乎只能删除区块数据重新同步，才能和主网同步。但是跑几个小时后又不同步了。用V1.0.0版本一周似乎没见到这个问题。目前退回到旧版试试

**Comment by cchanm** [comment]
你使用的那个commit，你使用bigbang -version查询一下版本号

**Comment by rlinxy** [comment]
> 你使用的那个commit，你使用bigbang -version查询一下版本号

V 1.0.1
最新的release
我现在已经退回去用旧版 V1.0.0了，昨天下午之前用1.0.0跑了一周，没发现这个情况，但是出现过一次segment fault自动停止，所以我尝试升级到 1.0.1，结果似乎又有新的同步问题。

**Comment by cchanm** [comment]
能否提供一下全部日志，用于分析

**Comment by rlinxy** [comment]
> 能否提供一下全部日志，用于分析

我看了一下日志，重新运行1.0.0版本后，之前日志被覆盖或者删除了，没注意
但是日志中基本都是不停重复我之前复制的那些

**Comment by rlinxy** [comment]
新版本目前看起来很稳定了
