### ISSUE TITLE
DPoS在txpool中的支持

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#370]
related to issue #355 

- [x] EnrollTx优先上链
- [x] EnrollTx需验证权重是否够资格
- [x] 对于不存在hashAnchor的EnrollTx不允许进入txpool，惩罚力度应比ddos小，且不删除inv
- [x] 同一个hashAnchor同一个地址只能有一个EnrollTx(目前hashAnchor是创世块,后面需要配合改动，功能实现但是暂时注释)
- [x] （优化）CTxSetChange的remove和update包含交易内容，以便consensus调用

**Comment by AlexiaChen** [comment]
目前跟这个issue相关，但是又舍去了一些地方 https://github.com/bigbangcore/BigBang/issues/277
