### ISSUE TITLE
DPoS delegate模板机制

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#372]
related to issue #355 

 - [ ] 增加赎回本金和验证，强限制：赎回该地址的交易不能有找零
 - [ ] 增加抵押本金交易最小额限制

**Comment by cchanm** [comment]
1. 登记地址、登记条件、登记过程：
登记地址：登记地址为delegate模板地址，该模板地址为其它用户投票的地址，destOwner赎回地址为登记用户的赎回地址，即登记模板地址中的两个地址都需要是登记用户的地址。
登记条件：登记是由节点自动完成，即产生CERT交易，但产生CERT交易的条件是delegate地址累计投票数需要超过最小投票数（如总量的2%），才能产生CERT交易，该限制在BLOCK较验时，也需要较验，不符合的BLOCK需要拒绝。
登记过程：要想成为DPOS节点，需要投票和登记参与DPOS节点竞争，用户需要生成一个登记地址，并布署到要成为DPOS的节点中，delegate模板地址的累计投票，记为登记地址的投票量。在CBlockBase:: VerifyDelegateVote该函数中，只有累计投票数达到最小投票数时，才记入mapEnrollTx表中，并写入数据库。在CConsensus::PrimaryUpdate中，只对投票数达到最小投票数时，产生成CERT交易。在BLOCK较验时，对CERT交易较验是否达到最小投票数。

1. 普通用户投票：
普通用户TOKEN数量不够独立成为DPOS节点时，可以向其它用户投票（成为DPOS节点的用户），通过累计投票量参与竞争。
普通用户投票时，需要生成投票模板地址，即vote模板地址，该模板地址中的delegate地址为投票地址，即参与竞争的delegate模板地址，而destOwner赎回地址为普通用户的赎回地址，用于普通用户赎回投票TOKEN使用。
普通用户向该模板地址转帐，即完成投票。
向vote模板地址转帐需要将delegate模板地址及赎回地址，保存到交易的签名参数中，用于较验和投票计算使用。

1. 赎回投票TOKEN：
用户（普通用户和DPOS登记用户）都可以将投票的TOKEN赎回，即转出，用户需要记住投票的vote模板地址和赎回地址的私钥，赎回时需要将vote模板地址和赎回地址的私钥导入，然后从该模板地址转出TOKEN即可。
赎回投票TOKEN后，相应的登记的delegate模板地址的累计投票数也减少（在CBlockBase:: VerifyDelegateVote函数中完成计算）。

1. 投票计算：
投票计算在CBlockBase:: VerifyDelegateVote函数中完成，主要对投票交易计算，即delegate模板地址和vote模板地址的转入和转出进行计算。
delegate模板地址的转帐，直接计算destIn和sendTo即可。
在投票转帐时，需要将vote模板地址的两个参数写入签名参数中，需要在CBlockBase:: VerifyDelegateVote函数中解板出delegate模板地址，再计算该参数的累计投票。

1. 登记交易（CERT交易）在BLOCK中的限制：
在一个BLOCK中，限制一个delegate模板地址只能有一条CERT交易，该限制在BLOCK较验时需要较验，不符合要求的BLOCK将拒绝。
该限制和最小投票TOKEN登记的限制，将有效的限制无成本CERT交易，一是产生CERT交易需要达到最小投票TOKEN数，二是同一个地址在一个BLOCK中只允许一条CERT交易。
