### ISSUE TITLE
DPoS在blockchain和core中的支持

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#373]
related to issue #355 

 - [ ] 将注释的关于dpos代码解开
 - [ ] ValidateTransaction检查TX_CERT类型
 - [ ] DPoS块在长链上的权重计算
 - [ ] 验证DPoS块的timestamp必须间隔前一个块60s，可防止恶意分叉构造长链
 - [ ] 链上数据保证同一个hashAnchor同一个地址只能有一个EnrollTx

**Comment by AlexiaChen** [comment]
开会讨论结果： 暂时不做，测试的时候再根据必要性修改
