### ISSUE TITLE
生产块规则及时间戳计算

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#415]
一、生产块规则：
1）DPOS选票随机选出一个地址生产块，该地址的节点生产完1分种的主链的块及子链主块和子块；
2）DPOS块的时间戳
 - 主链块，如果`(DPoS块高度 - 最近的DPoS块高度) * 60s > 前一个块的时间戳`，则当前块时间戳为`(DPoS块高度 - 最近的DPoS块高度) * 60s`，否则当前块时间戳为`前一个块 + 60s`
 - 子链的主块时间戳，必须与同高度的主链块时间戳相同
 - 子块的时间戳是前一块的时间戳+2，即子块的时间戳间隔为2，该时间戳要块较验时较验；
3）节点需要出完子链的30个块（包括1个主块，29个子块，共30块），即使没有交易，也需要生产子块；
4）节点计算共识时间为：先假定当前块为DPoS，共识时间 = DPoS块时间戳 - 5s
4）如果共识结果是DPOS块，节点就可以生产块，并在时间戳时广播，其它节点较验时，只要`接收时间 + 20s > DPoS块的时间戳`，即较验通过；
5）如果共识结果为POW，则主链可以立即生产PoW块和广播，子链由于是生产前一高度的空块，所以本高度不做操作。

二、子链生产块规则
1）当主链生产了DPOS块后，子链可以生产块；
2）子链主块与主链DPOS块时间戳相同，子块的时间戳是前一块的时间戳+2，即子块的时间戳间隔为2；
3）子链1分钟需要产生30个块（包括1个主块，29个子块，共30块），即使没有交易，也需要生产子块；
4）节点需要等待前一高度的最后一个子块（即29号子块，0号块为子链主块），等待时长为50秒（时间点为本高度主块的时间戳+50）；如果50秒前收到前一高度的最后一块，则从该块开始生产块；如果超时未收到，则从节点当前的最后一块之后生产块，并可连续生产块，生产时间可以为下高度主块的时间戳+50之前；
5）如果未收到前一高度的最后一块，则节点在生产本高度的主块时，需要先生产前一高度缺失的子块，使用空子块填充，每个空子块的权重为0，空子块需要广播；
6）非生产节点在收到空子块时，需要较验接收时间，如果接收时间小于本高度的主块时间戳+50秒，则拒绝接收，但不产生DDOS，如果接收时间小于本高度的主块时间戳+30秒，则拒绝接收，并产生DDOS；
7）非生产节点在本高度的主块时间戳+30秒内，收到前一高度的最后块，则优先使用前一高度的最后块，如果50秒后收到空子块，则拒绝接收该空子块；如果在本高度的主块时间戳+30秒后收到上一高度的最后块，则不优先使用，50秒后收到空子块，则优先使用该空子块；

注：子链的权重计算的Weight值固定为23。

例：
1）假设：100高度由A节点生产子链块，101高度由B节点生产子链块，102高度由C节点生产子链块；
2）B节点在101高度的主块时间戳+50秒之前需要等待100高度的最后一块（即29号子块），如果超时时，只收到了27号子块，则B节点生产上一高度的28、29号空子块，然后再生产101高度的主块，以及子块；
3）如果C节点在101高度的主块时间戳+30秒之前收到100高度的最后一块（即29号子块），则优先使用该块，如果在50秒之后收到B节点的28、29号空子块，C节点将拒绝接收，并且C节点在102高度时，从100高度的29号子块之后生产，并在101高度生产一块空主块，然后再生产102高度的块；如果在30秒之后收到上一高度的最后块，并且50秒之后收到B节点的28、29号空子块，将优先接收28、29号空子块；

三、节点生产块逻辑：
1）节点计算共识后，如果是DPOS生产块，则开始生产主链的DPOS块，然后生产子链的块，如果前一块为DPOS块，则节点需要等待最后一个子块，等待超时时长为50，即前一块时间戳+60+50时间之后为超时，如果超时，节点从子链最后一块开始生产子链块。如果前一块为POW块，则不需要等待最后块，立即生产子链块。
2）如果计算共识为POW，则在计算共识后就可以计算HASH，并可以生产块广播。

四、节点较验逻辑：
1）较验主链BLOCK时间戳：
较验一：如果本块为DPOS块，则按`DPOS块的时间戳规则`强校验；如果是POW块，则本块时间戳>前一块时间戳。
较验二：本块的时间戳 < 当前网络时间+20。

2）较验子链BLOCK时间戳：
较验一：子链主块时间戳=主链同高度的块时间戳。
较验二：同高度子链的主块时间戳<子链子块时间戳<同高度子链的主块时间戳+60。
较验二：子链子块时间戳=前一块时间戳+2，前一块为本高度的子链主块或子块。

五、生产块逻辑图：
![image](https://user-images.githubusercontent.com/45554027/76216364-6ed8e980-624b-11ea-8b38-b9ae1dd8fb06.png)

六、子链生产块示意图：
![image](https://user-images.githubusercontent.com/45554027/77154770-508aad80-6ad7-11ea-8a92-2bff5f54bec9.png)

**Comment by sunhantao** [comment]
除了空子块等防作弊规则外已提交

**Comment by AlexiaChen** [comment]
相关代码分支已经合并，关闭。
