### ISSUE TITLE
改造netchannel为消息模型

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#43]
- [x] 改造netchannel为消息模型
 - [x] 在消息模型下，评估是否需要多线程的netchannel，因为耗时久的地方在txpool和blockchain

应该不需要多线程，改造成消息模型以后

Related to #40

**Comment by AlexiaChen** [comment]
- [x] 阅读BTC [netprocessing源码](https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp) ，它相当于本项目NetChannel的功能
-  [x] 梳理NetChannel的数据结构
- [x] 完成PeerNet传过来的事件改造成消息（Active Deactive GetBlocks GetData等）
- [x] PeerNet向NetChannel发布消息，NetChannel向PeerNet DispatchEvent暂时保留，测试过以后再改成发布消息模式
- [x] DispatchEvent也改成消息模式(NetClose NetReward GetBlocks GetData等)
- [x] NetChannel单元测试
- [x] 集成测试

**Comment by AlexiaChen** [comment]
![NetChannel数据结构关系图](https://user-images.githubusercontent.com/8574915/64759777-b74c6e80-d56a-11e9-9547-bbae97f68e91.png)
