### ISSUE TITLE
listkey中timeout值为负数

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#457]
在采用非debug方式启动时，CORE具有WALLET自动加锁的功能，但使用listkey查询时，timeout出现了负数，并且负数的数值越来越大。

bigbang> listkey 
[
    {
        "key" : "d032d6c7ad3f7404e0655f3b821d2b0574c70518e2f1fd9b6810e0607d1eba83",
        "version" : 1,
        "public" : false,
        "locked" : false,
        "timeout" : -4966
    }
]

bigbang> unlockkey d032d6c7ad3f7404e0655f3b821d2b0574c70518e2f1fd9b6810e0607d1eba83 123 10
{
    "code" : -409,
    "message" : "Key is already unlocked"
}

bigbang> lockkey d032d6c7ad3f7404e0655f3b821d2b0574c70518e2f1fd9b6810e0607d1eba83
Lock key successfully: d032d6c7ad3f7404e0655f3b821d2b0574c70518e2f1fd9b6810e0607d1eba83

如果：
unlockkey d032d6c7ad3f7404e0655f3b821d2b0574c70518e2f1fd9b6810e0607d1eba83 123 5
这样之后，还会出现负数

**Comment by AlexiaChen** [comment]
之前和@sunhantao一起查看复现，但是复现不出来，现在打算打算再次尝试复现。

**Comment by sunhantao** [comment]
有可能是读锁内更新自动锁定时间，由并发操作导致了数据错乱，没有触发锁定。应该把更新自动锁定时间包含在写锁内。由于并发问题，很难复现
