### ISSUE TITLE
改造service为消息模式

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#47]
- [x] 考虑service模块的必要性
- [x] 改造service为消息模式

Related to #40

**Comment by AlexiaChen** [comment]
我看了下CService模块，其中确实用到了DispatchEvent的同步特性，如果改成消息模式纯异步，这样设计和代码可读性可能会降低。当然，可以考虑用promise和future来适当解决这个问题

**Comment by sunhantao** [comment]
在service里面，需要同步的地方有两种：
 - 一种是读取类，当对应的模块剥离出数据模块，可以直接读数据模块，是同步的
 - 一种是写入类，写入类都是写过去就不管了，像SendTransaction

有发现超出这个规律的吗

**Comment by AlexiaChen** [comment]
@sunhantao   数据类，有些要去网络层拿，或者去Wallet等其他模块去主动去取（同步调用）。除非等到数据全部分离出来，不然现在不太好改。要延后些。

**Comment by sunhantao** [comment]
嗯，是的。service也要分离出actor和数据层，actor只接受更新块的数据
