### ISSUE TITLE
如何开启rpc外部访问

### ISSUE THREAD

**Issue by OctoberSouth** [bigbangcore/BigBang#481]

**Comment by AlexiaChen** [comment]
-rpcallowip=*.*.*.* -rpcport=[ip port]

**Comment by OctoberSouth** [comment]
> -rpcallowip=_._._._ -rpcport=[ip port]

试了没用呀，加了后命令都无法访问

**Comment by AlexiaChen** [comment]
> 
> 
> > -rpcallowip=_._._._ -rpcport=[ip port]
> 
> 试了没用呀，加了后命令都无法访问
-rpcallowip=\*.\*.\*.*

刚才没有转义，符号被吃了。

**Comment by AlexiaChen** [comment]
@OctoberSouth   It works now?

**Comment by OctoberSouth** [comment]
> @OctoberSouth It works now?

可以了
