### ISSUE TITLE
由于同步block的超时时间很长，在等待时出现不停同步mint交易并丢弃的情况

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#486]
- 由于所有的block在同步过程中，ScheduleBlockInv会返回空，此时会同步交易。
 - 如果同步的交易前序是mint，收到交易后会请求mint交易。
 - 接收了mint交易后，netchannel会丢弃它。
 - 后续会不停的同步该mint交易，直到block同步超时或返回。但是现在超时时间很长（600s），而且ping/pong消息没有超时机制

**Comment by cchanm** [comment]
之前的日志还在吗，发给我分析一下

**Comment by cchanm** [comment]
1）如果块未接收到，但块的mint tx的后序tx接收了，会因缺少前序而添加一条tx inv，然后去同步，后面接收到该TX数据时，发现是mint，则会丢掉；
2）主动添加inv，是在接收到TX时，因缺少前序才添加INV，只在接收到TX时才会添加，所以mint tx inv，只因该TX的后序TX被接收时才添加INV，当MINT TX后序TX还在缓存中，则不会被再添加INV，而MINT TX的后序TX会被缓存7200秒，所以在这7200秒内不会才添加MINT TX INV，所以不会快速的同步MINT TX；
3）当前接收到该块时，会对schedule移除块中的交易及mint tx交易，并且会提交后序交易，所以MINT TX的后序交易会在该块接收时会提交；

**Comment by cchanm** [comment]
如果对端主动发送一条MINT TX INV，本端会去请求该TX数据，并接收到丢掉，然后对端又主动发送一条MINT TX INV，本端又去请求TX数据，这样反复快速请求，这种情况会消耗网络和CPU资源，这种情况只是对端修改代码故意发送MINT TX INV，属于恶意行行为，针对这种情况，可以修改接收到的MINT TX不马上移除，延迟180秒才移除，这样对端再发送MINT TX INV，因本端已有该INV而不再接收，就解决了快速同步消耗网络和CPU资源的问题。
