### ISSUE TITLE
开多个DPOS节点，DPoS不稳定，DPoS和PoW共识会频繁切换

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#5]
当pow的难度低，分发新块的时间低于1分钟，会出现issue这种现象。

**Comment by shangqd** [comment]
bigluashell exec new 0 2 200000000
而且一旦从DPoS切换到PoW，就需要花很长时间切换到Dpos了，测试的分支是DPOS-3-6

**Comment by sunhantao** [comment]
Fixed
