### ISSUE TITLE
通过bigbang getblockdetail命令查询数据出错的问题

### ISSUE THREAD

**Issue by chajiubu** [bigbangcore/BigBang#501]
数据重新同步过，且高度已经与当前全网区块高度一致，但是数据同步中某些交易出问题后并没有正确处理，再次同步也不能修复。

下边这个块是我发现的一个出问题的块：0003047c7e9fb5d6cd13c01d34ffb6cf59654fba3c9d2da1f98be6764eeeeaf2

表现为在当前机器上使用getblockdetail 0003047c7e9fb5d6cd13c01d34ffb6cf59654fba3c9d2da1f98be6764eeeeaf2 返回错误，进一步查看交易发现其中有一个交易不正常，如下：
getblockdetail 0003047c7e9fb5d6cd13c01d34ffb6cf59654fba3c9d2da1f98be6764eeeeaf2
{
    "code" : -32603,
    "message" : "No information available about the previous one of this block's mint transaction"
}

但是：
getblock 0003047c7e9fb5d6cd13c01d34ffb6cf59654fba3c9d2da1f98be6764eeeeaf2
{
    "hash" : "0003047c7e9fb5d6cd13c01d34ffb6cf59654fba3c9d2da1f98be6764eeeeaf2",
    "hashPrev" : "0003047badd1449543639e8392832392a8f62464154bf7306a663501e8e6b5f9",
    "version" : 1,
    "type" : "primary-dpos",
    "time" : 1586828535,
    "fork" : "00000000b0a9be545f022309e148894d1e1c853ccac3ef04cb6f5e5c70f41a70",
    "height" : 197756,
    "txmint" : "**5e9514f707ee78cf61e55180636330ce8ad160087431a880d3a3a1ada4037063**",
    "tx" : [
        "5e9514e1e98a86a1fae29b6876bc9906af2dfa318fd8d8a6a415f9ba89c01e15",
        "5e9514e1a18e71690b60f0f71a5615426183810b9b082c32e13ecf67ecddd382",
        "5e9514e2a28a1d9c3a1d28ab749357692d1dca9a59ed7bbd95d36a8ea586e72d",
        "5e9514e22eab23a0e52062bd7b9428572ff4ac4b48d1b7de67420d2abb9928d9"
    ],
    "prev" : "0003047badd1449543639e8392832392a8f62464154bf7306a663501e8e6b5f9"
}

查看交易，发现有不正常的交易：
gettransaction 5e9514f707ee78cf61e55180636330ce8ad160087431a880d3a3a1ada4037063
{
    "code" : -32600,
    "message" : "No information available about transaction"
}

但是在另外的机器上通过相同的方式查询，结果显示都正常

下边的图片是操作过程：
链接：https://pan.baidu.com/s/1vvZphzrrsiEMS3b07cZmkg 
提取码：bmg9

程序版本：7a82e87bd6c88be58667f7f31e9988d300b24fcf

区块数据打包：
链接：https://pan.baidu.com/s/1T7GPBFwor6Z-zNYmWraE3g 
提取码：lfqk

**Comment by AlexiaChen** [comment]
貌似 新PR #500 已经解决，这个问题了。

**Comment by AlexiaChen** [comment]
下载完毕数据，并且，把commit切换到描述所述，现在能正常复现，而且这个sender代码原来就有问题，同样也处理不了创世块的mint tx。后续继续验证调试。

**Comment by AlexiaChen** [comment]
通过gettransaction，打日志发现，mint tx 5e9514f707ee78cf61e55180636330ce8ad160087431a880d3a3a1ada4037063 在LevelDB中的CTxIndex没有被找到，由此需要查看下以前额日志，看啊可能以前的bigbang-core有没有被不正常结束终止。

**Comment by AlexiaChen** [comment]
查看了数据压缩包里面的logs-collector里面的日志，bigbangc-core操作正常，没有不正常的重启，因为Initialize和Deinitialize一一对应，没有不匹配的现象。所以CTxIndex应该不会丢失没存进去LevelDB才对。

**Comment by chajiubu** [comment]
> 查看了数据压缩包里面的logs-collector里面的日志，bigbangc-core操作正常，没有不正常的重启，因为Initialize和Deinitialize一一对应，没有不匹配的现象。所以CTxIndex应该不会丢失没存进去LevelDB才对。

这是数据同步过程中产生的，同步数据TX丢失了，但是block还在。考虑下数据同步的问题。

**Comment by AlexiaChen** [comment]
> 
> 
> > 查看了数据压缩包里面的logs-collector里面的日志，bigbangc-core操作正常，没有不正常的重启，因为Initialize和Deinitialize一一对应，没有不匹配的现象。所以CTxIndex应该不会丢失没存进去LevelDB才对。
> 
> 这是数据同步过程中产生的，同步数据TX丢失了，但是block还在。考虑下数据同步的问题。

嗯，正准备，查看相关mint tx的id，再跟踪下历史日志记录，看看是怎样的。

**Comment by AlexiaChen** [comment]
> 
> 
> > 查看了数据压缩包里面的logs-collector里面的日志，bigbangc-core操作正常，没有不正常的重启，因为Initialize和Deinitialize一一对应，没有不匹配的现象。所以CTxIndex应该不会丢失没存进去LevelDB才对。
> 
> 这是数据同步过程中产生的，同步数据TX丢失了，但是block还在。考虑下数据同步的问题。

好的，后序跟踪下mint tx的dpos block在日志中是怎样流转的。

---------------

现在最新的情况是，后序的dpos-block中的普通被打包的tx，个别tx也找不到，也是CTxIndex有问题

getblock 0003047d0f9c42e52bac53c92e4b269d0d2ffefc0c6e988f8664b6ed3685df29

该块是描述中的下一个primary-dpos区块，这个区块中打包的4个普通交易，有三个是不存在的:

```txt
 "tx" : [
        "5e9514f7cc241e97c3795202ce22604f03f042379234c929015429b90a596b53",
        "5e9514f7ed15438086bcf14509f1b8b887f51e87a76f815bd9ac867cb4903bfb",
        "5e9514f75fdcdb162f46f6766ffa7c57be1181026eea4ce67f5a6670a60b4bca",
        "5e9514f7859b0acb0cc3bd87b46949d3209333072c4c51d78ea2e27ee1ffa3e3"
    ],
```

其中，前三个是不存在的，CTxIndex没有。

**Comment by AlexiaChen** [comment]
@chajiubu   你给的数据的日志，是不是没有用debug，日志信息量太少，我想通过日志找tx id都找不到NetChannel的层面。我现在只有重新，清了数据，尝试复现了。

**Comment by chajiubu** [comment]
@AlexiaChen 是debug的。你看里面有很多dubug标志

**Comment by AlexiaChen** [comment]
> 
> 
> @AlexiaChen 是debug的。你看里面有很多dubug标志

我落实了，是的，是debug的。但是奇怪的是居然找不到这些有问题的tx和block的相关同步日志，只有rpc的。线索断了，我先试着清了同步数据。

**Comment by cchanm** [comment]
这个问题是由于TXINDEX错误，所以查询不到该交易，而启动时checkrepair只较验了最近128块，出现的交易所在块高度为197756，超过了128，所以未较验到，把这个128限制注释掉，再启动就可以查询到了（已试验）。

**Comment by chajiubu** [comment]
@cchanm 那这有个问题啊  如果高度很高的话，这个校验岂不是要花更多的时间去做？那启动是不是就更慢了？
