### ISSUE TITLE
主链块回滚后，可能导致分支块的CProofOfPiggyback::hashRefBlock不再是长链块

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#554]
- 分支链高度h的subsidiary及extended块的proof中包含了hashRefBlock字段，如果主链高度h的块发生了回滚，则分支高度h的块引用的块不再是主链的长链，此时应该相应的创建空块并设置为长链。

 - 需要考虑主链再次回滚后的支链块如何恢复

**Comment by cchanm** [comment]
1、通过主链块的变化，同步修正子链的长链；
2、当前程序中有块高度表，即可以查询指定高度的相关块，包括长链和短链的块；
3、子链生产块时，需要具有修复错误的最后一块的功能，即在生产子链块时，需要查询前一块的参考块是否为长链，如果不是，则需要修正子链的最后一块；
4、较验子链块时，需要较验前一块（非空块）的参考主链块，与本块的参考主链块是否为同一条链上，如果不是，则较验失败；
5、如果添加的子链块参考的主链块不是长链，则该子链块将不通过权重来计算长链，即该块直接作为短链块，不管权重是多少；
