### ISSUE TITLE
blockmaker产生支链块时，找不到前序块

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#574]
这个问题分两种情况
 - 前序是非空块：blockmaker会等待50秒（如果主链前序是dpos块）
 - 前序块是空块：产生空块的代码`CDispatcher::SyncForkHeight`中有判断netchannel的同步状态`!pNetChannel->IsForkSynchronized(hashFork)`。这个目的是为了防止未同步完之前，不停的产生新的空块链和回滚。针对这种情况可以考虑增加一个判断：如果( 主链高度 - 支链高度 ) < N，那么就不必理会是否同步的标记，直接产生后续的空块

**Comment by cchanm** [comment]
日志信息：
2020-07-06 02:45:08.333004 : [bigbang] <error> {blockmaker} - <blockmaker>ProcessSubFork get last block error, fork: 0000001f9a046730bf5102283f43fe51bd1c1b913b3b931c1566d9c5e1463a7e

问题分析：
1、不生产子链块，是因为ProcessSubFork函数中的GetLastBlockOfHeight失败导致的，GetLastBlockOfHeight函数失败可能的原因是pIndex->GetBlockHeight() < nHeight，即支链最后一块的高度小于前一高度；
2、前一高度未生产空块，可能是CDispatcher::SyncForkHeight因pNetChannel->IsForkSynchronized(hashFork)为FALSE，所以没有生产空块；
3、BLOCKMAKER与CDispatcher::SyncForkHeight存在逻辑上的冲突，CDispatcher::SyncForkHeight在有同步时，不生产空块，而BLOCKMAKER认为前一块肯定存在，所以产生了这个错误。

解决方案一：
1、BLOCKMAKER与CDispatcher::SyncForkHeight存在逻辑上的冲突，如果CDispatcher::SyncForkHeight不生产支链前一高度的空块，则在BLOCKMAKER的ProcessSubFork函数则找不到前序块，并且BLOCKMAKER没有生产前序空块的功能；
2、改为子链空块由后面生产子链块的节点完成，即节点要生产本高度的子链主块时，如果前序未不存在，则生产所有前序的空块，满跳自已生产子链主块的需求，所以子链空块都由生产子链主块的节点生成，其它节点都不生成；
3、子链空块需要广播（当前没有广播），不生产块的节点，只能同步其它节点的空块；
4、该方案把子链空块生产权交给子链生产节点，而之前是在主链块产生时调用CDispatcher::SyncForkHeight完成，是子链空块生交权是主链节点完成，将空块权限交给子链节点，有利于超级节点的实施；
5、由于生产子链主块有延时功能，相当于有了同步等待功能，所以之前的IsForkSynchronized就必要性不大了；

**Comment by sunhantao** [comment]
可以考虑子链和主链一定高度范围内不考虑IsForkSynchronized状态

**Comment by cchanm** [comment]
空块较验规则：
1、检查点以前的高度接收到分叉空块，则直接丢掉，因为检查点以前高度的块已确认，不可能有分叉，所以再接收到分叉空块，则是不合法的块，该较验失败不产生DDOS；
2、检查点之后的高度接收到的空块，可以接收，但需要较验空块的参考主链块的HASH是否正确；
3、空块增加参考主链块参数，即同子链主块或子块一样，在vchProof中增加参考字段，较验时，需要较验参考主链的块是否存在；
4、空块在AddNewBlock函数里，不做回滚计算，不做长链计算，只需要块较验通过后，添加到链上即可（因为空块没有交易，也没有权重）；

该规则实现有限的攻击防犯：
1、攻击只能在检查点之后发送空块，只有指定高度的主链有块的时候才有一个空块，并且一个主链块，只能有一个空块，产生的空块数，最多为检查点之后的主链块数，所以攻击有限；
2、空块只会占用BLOCK文件及BLOCKINDEX，不会产生回滚计算攻击；
