### ISSUE TITLE
修改出块奖励分布

### ISSUE THREAD

**Issue by sunhantao** [bigbangcore/BigBang#69]
See [出块奖励分布](https://github.com/bigbangcore/BigBang/wiki/出块奖励分布)

**Comment by cchanm** [comment]
已完成修改和测试，公测的TOKEN分布作了调整，正式的TOKEN分布值被注释，后面正式上线之前，把注释去掉即可。

**Comment by sunhantao** [comment]
@cch809094 Token分布又做了修改，修改部分：
 - PoW的出块奖励
 - DPoS+PoW的出块奖励
 - 基金会、技术团队释放方式数值调整
 - 市场运营释放方式数值调整

[出块奖励分布](https://github.com/bigbangcore/BigBang/wiki/%E5%87%BA%E5%9D%97%E5%A5%96%E5%8A%B1%E5%88%86%E5%B8%83)
